version: '3'
services: 
    es-node1:
        image: elasticsearch:6.8.0
        container_name: es-node1
        restart: always
        environment: 
            - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
        ulimits: 
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536 
        volumes: 
            - ./conf/es-node1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./data:/usr/share/elasticsearch/data
            - ./logs:/usr/share/elasticsearch/logs
            - ./plugins/analysis-ik:/usr/share/elasticsearch/plugins/analysis-ik 
        network_mode: host